using MetaLoop.Common.PlatformCommon;
using MetaLoop.Common.PlatformCommon.Data;

using SQLite4Unity3d;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Text;
using System.Threading.Tasks;

namespace MetaLoopDemo.Meta.Data
{
    //[MetaAutoGenerated]
    //public class AbilityData : IMetaDataObject
    //{

    //    [PrimaryKey, AutoIncrement]
    //    public int Id { get; set; }

    //    [MetaUniqueField]
    //    public string AbilityName { get; set; }
    //    public float Damage { get; set; }
    //    public float Duration { get; set; }
    //    public string AnimationId { get; set; }

    //}
}
