using MetaLoop.Common.PlatformCommon.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MetaLoopDemo.Meta.Data
{
    public enum ConsumableType
    {
        Undefined, 
        Elixir,
        Shard,
        VariableTroopShard,
        VariableFactionShard
    }

    [MetaAutoGenerated("ConsumableData")]
    [MetaSchemaOrder(-1001)]
    public class Consumable : MetaLoop.Common.PlatformCommon.Data.Schema.Consumable, IMetaDataObject
    {
        public ConsumableType Type { get; set; }
        
    }
}
