using MetaLoop.Common.PlatformCommon.Data;
using MetaLoop.Common.PlatformCommon.Data.Schema;
using SQLite4Unity3d;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Text;
using System.Threading.Tasks;

namespace MetaLoopDemo.Meta.Data
{
    public enum TierType
    {
        Undefined,
        Common,
        Uncommon,
        Rare,
        RarePlus,
        Epic,
        EpicPlus,
        Legendary,
        LegendaryPlus,
        Mythic,
        MythicPlus,
        Ascended,
        AscendedPlus,
        Ultimate
    }


    [MetaAutoGenerated]
    [MetaSchemaOrder(-1000)]
    public class TierData : CostObject, IMetaDataObject
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        [MetaUniqueField]
        public TierType Tier { get; set; }
        public int LevelCap { get; set; }
        public float StatBoost { get; set; }
    }
}
