using MetaLoop.Common.PlatformCommon.Data;

using SQLite4Unity3d;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Text;
using System.Threading.Tasks;

namespace MetaLoopDemo.Meta.Data
{
    public enum TagType
    {
        Undefined,
        Faction,
        Role
    }

    [MetaAutoGenerated]
    [MetaSchemaOrder(-1000)]
    public class TroopTagData : IMetaDataObject
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        [MetaUniqueField]
        public string TagName { get; set; }
        public TagType TagType { get; set; }

    }
}
