using System;
using System.Collections.Generic;
using System.Text;

namespace MetaLoop.Common.PlatformCommon.Data
{
    public class MetaAutoGenerated : Attribute
    {
        private string dataTableName;
        public string Name
        {
            get { return dataTableName; }
        }
        public MetaAutoGenerated() { }
        public MetaAutoGenerated(string dataTableName) { this.dataTableName = dataTableName; }
    }
}
