using System;
using System.Collections.Generic;
using System.Text;

namespace MetaLoop.Common.PlatformCommon.Data
{
    public class MetaAutoGeneratedAllowNull : Attribute
    {
        public MetaAutoGeneratedAllowNull() { }

    }
}
